import { Playpen_Sans, Rubik_Dirt } from "next/font/google";
import "./globals.css";

const playpenSans = Playpen_Sans({
  variable: "--font-cute",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const rubikDirt = Rubik_Dirt({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playpenSans.variable} ${rubikDirt.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
